[features]
seeds = false
skip-lint = false

[programs.localnet]
carbon_credit_program = "41jbriQNyaJLuUfJWennbwVqGTQeBDc94Ywj4pGBarnv"

[programs.devnet]
carbon_credit_program = "41jbriQNyaJLuUfJWennbwVqGTQeBDc94Ywj4pGBarnv"

[provider]
cluster = "Devnet"
wallet = "phantom-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/*"
]

[test]
startup_wait = 10000
