import {
  IsInt,
  IsNumber,
  IsOptional,
  IsString,
  Matches,
  MaxLength,
  Min,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { ListingStatus, ProjectType } from '@prisma/client';

const BASE58 = /^[1-9A-HJ-NP-Za-km-z]{32,44}$/;

/** A Solana transaction signature: 64 bytes base58-encoded (87-88 chars). */
const BASE58_SIGNATURE = /^[1-9A-HJ-NP-Za-km-z]{87,88}$/;

/** POST /marketplace/listings — create a listing. */
export class CreateListingDto {
  @ApiProperty({
    description: 'On-chain credit identifier (mint / batch address, base58).',
    example: '6Bfx...',
  })
  @IsString()
  @Matches(BASE58, { message: 'creditId must be a valid base58 Solana address' })
  creditId: string;

  @ApiProperty({
    description: 'Seller wallet (base58) — must be the connected wallet and current credit owner.',
    example: 'HNDAhSqXTA6woJLRRQpaMsWX171XVsjgxBXRxz95xfSB',
  })
  @IsString()
  @Matches(BASE58, { message: 'seller must be a valid base58 Solana address' })
  seller: string;

  @ApiProperty({ description: 'Sale price (USDC / platform unit).', example: 24.5 })
  @IsNumber()
  @Min(0.000001, { message: 'price must be greater than 0' })
  price: number;

  @ApiPropertyOptional({ description: 'Credits (tonnes) offered.', example: 100, default: 1 })
  @IsOptional()
  @IsInt()
  @Min(1)
  amount?: number;

  @ApiPropertyOptional({ description: 'Originating project id (uuid).' })
  @IsOptional()
  @IsString()
  projectId?: string;

  @ApiPropertyOptional({ example: 'Amazon Reforestation Block A' })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  projectName?: string;

  @ApiPropertyOptional({ enum: ProjectType })
  @IsOptional()
  @IsString()
  projectType?: ProjectType;

  @ApiPropertyOptional({ example: 'VM0036' })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  methodology?: string;

  @ApiPropertyOptional({ example: 2026 })
  @IsOptional()
  @IsInt()
  @Min(1)
  vintage?: number;

  @ApiPropertyOptional({ example: 1250.7 })
  @IsOptional()
  @IsNumber()
  verifiedTonnes?: number;

  @ApiPropertyOptional({ example: 'bafy...' })
  @IsOptional()
  @IsString()
  reportCid?: string;
}

/** POST /marketplace/listings/:id/buy — purchase a listing. */
export class BuyListingDto {
  @ApiProperty({
    description: 'Buyer wallet (base58) — the connected wallet authorizing the purchase.',
    example: 'HNDAhSqXTA6woJLRRQpaMsWX171XVsjgxBXRxz95xfSB',
  })
  @IsString()
  @Matches(BASE58, { message: 'buyer must be a valid base58 Solana address' })
  buyer: string;

  @ApiPropertyOptional({
    description:
      'Seller signing secret (JSON array / base58 / csv) for server-side settlement. Only used in the automated / managed-custody flow. In the production client-signed flow the frontend signs the prepared tx instead.',
  })
  @IsOptional()
  @IsString()
  sellerSecret?: string;

  @ApiPropertyOptional({
    description:
      'Already-submitted on-chain transfer signature (client-signed flow). When present, the backend records it as the settlement proof and performs no further chain write. Mutually exclusive with sellerSecret.',
  })
  @IsOptional()
  @Matches(BASE58_SIGNATURE, { message: 'txSignature must be a valid base58 Solana signature' })
  txSignature?: string;
}

/** POST /marketplace/listings/:id/cancel — cancel a listing. */
export class CancelListingDto {
  @ApiProperty({
    description: 'Wallet requesting the cancel (base58) — must equal the listing seller.',
    example: 'HNDAhSqXTA6woJLRRQpaMsWX171XVsjgxBXRxz95xfSB',
  })
  @IsString()
  @Matches(BASE58, { message: 'seller must be a valid base58 Solana address' })
  seller: string;
}

/** POST /marketplace/seller-keys — provision a server-side settlement key. */
export class ProvisionSellerKeyDto {
  @ApiProperty({
    description:
      'Seller main wallet (base58) — must be the wallet linked to the authenticated VerdiCred user.',
    example: 'HNDAhSqXTA6woJLRRQpaMsWX171XVsjgxBXRxz95xfSB',
  })
  @IsString()
  @Matches(BASE58, { message: 'walletAddress must be a valid base58 Solana address' })
  walletAddress: string;
}

/** POST /marketplace/seller-keys/:id/confirm — confirm custody with a wallet signature. */
export class ConfirmSellerKeyDto {
  @ApiProperty({
    description:
      'The exact challenge message the seller signed (generated by the frontend and prefixed with "VerdiCred Marketplace Settlement Key").',
  })
  @IsString()
  message: string;

  @ApiProperty({
    description: 'ed25519 signature over `message` by the seller wallet (base64).',
  })
  @IsString()
  signature: string;
}

/** POST /marketplace/listings/:id/deposit-confirm — verify a seller deposit landed. */
export class DepositConfirmDto {
  @ApiProperty({
    description:
      'On-chain `transferCredit` signature moving the listed credits from the seller wallet to the custody ATA (base58).',
  })
  @IsString()
  @Matches(BASE58_SIGNATURE, { message: 'txSignature must be a valid base58 Solana signature' })
  txSignature: string;
}

/** A provisioned seller settlement key as returned by the API (public fields only). */
export class SellerKeyResponseDto {
  @ApiProperty() id: string;
  @ApiProperty() walletAddress: string;
  @ApiProperty({ description: 'Custody keypair public key (base58) — the settlement signer.' })
  publicKey: string;
  @ApiProperty({ description: "Token-2022 ATA of the custody key (deposit target)." })
  ata: string;
  @ApiProperty({ enum: ['ACTIVE', 'REVOKED'] }) status: string;
  @ApiProperty() confirmed: boolean;
  @ApiProperty() createdAt: string;
}

/** Result of verifying a deposit attempt. */
export class DepositCheckDto {
  @ApiProperty() funded: boolean;
  @ApiProperty() custodyBalance: number;
  @ApiProperty() amount: number;
}

/** A listing as returned by the API. */
export class ListingResponseDto {
  @ApiProperty() id: string;
  @ApiProperty() creditId: string;
  @ApiProperty() seller: string;
  @ApiPropertyOptional({ nullable: true }) buyer: string | null;
  @ApiProperty() price: number;
  @ApiProperty() amount: number;
  @ApiProperty({ enum: ['ACTIVE', 'SOLD', 'CANCELLED'] }) status: ListingStatus;
  @ApiPropertyOptional({ nullable: true }) projectId: string | null;
  @ApiPropertyOptional({ nullable: true }) projectName: string | null;
  @ApiPropertyOptional({ nullable: true }) projectType: ProjectType | null;
  @ApiPropertyOptional({ nullable: true }) methodology: string | null;
  @ApiPropertyOptional({ nullable: true }) vintage: number | null;
  @ApiPropertyOptional({ nullable: true }) verifiedTonnes: number | null;
  @ApiPropertyOptional({ nullable: true }) reportCid: string | null;
  @ApiPropertyOptional({ nullable: true }) txSignature: string | null;
  @ApiPropertyOptional({ nullable: true }) explorerUrl?: string | null;
  @ApiPropertyOptional({ nullable: true }) settledAt: string | null;
  @ApiPropertyOptional({ nullable: true }) metadata?: unknown;
  @ApiPropertyOptional({
    nullable: true,
    description: 'Server-side settlement (custody) key public key for the listing seller.',
  })
  custodyPublicKey?: string | null;
  @ApiPropertyOptional({ nullable: true, description: 'Custody ATA where listed credits are deposited.' })
  custodyAta?: string | null;
  @ApiPropertyOptional({ nullable: true, description: 'True when the custody ATA holds at least `amount` credits.' })
  custodyFunded?: boolean | null;
  @ApiPropertyOptional({ nullable: true, description: 'True when the seller has a confirmed settlement key.' })
  sellerKeyReady?: boolean | null;
  @ApiProperty() createdAt: string;
  @ApiProperty() updatedAt: string;
}
